version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 954747465428.dkr.ecr.us-west-2.amazonaws.com
      - python -m pytest tests/ --junitxml=pytest-report.xml || true

  build:
    commands:
      - docker build -t flask-app:latest -f Dockerfile.prod .
      - docker tag flask-app:latest 954747465428.dkr.ecr.us-west-2.amazonaws.com/flask-app-repo:latest

  post_build:
    commands:
      - docker push 954747465428.dkr.ecr.us-west-2.amazonaws.com/flask-app-repo:latest
      - echo '[{"name":"flask-app","imageUri":"954747465428.dkr.ecr.us-west-2.amazonaws.com/flask-app-repo:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - pytest-report.xml